### ISSUE TITLE
When enable minify,  it print error "Library class android.content.res.XmlResourceParser implements program class org.xmlpull.v1.XmlPullParser"

### ISSUE THREAD

**Issue by storytellerF** [thegrizzlylabs/sardine-android#70]
>AGPBI: {"kind":"error","text":"Library class android.content.res.XmlResourceParser implements program class org.xmlpull.v1.XmlPullParser","sources":[{}],"tool":"R8"}

**Comment by jacobras** [comment]
This is because this library depends on the Simple XML parser (`org.simpleframework:simple-xml`), which uses `XmlPullParser`. The library maintainer could consider replacing it. For us as consumers, we can ignore this error by configuring ProGuard.

I have the following lines in my release config, but I think only the last one is really needed: don't warn about this library using the `XmlResourceParser` (indirecty through Simple XML). Let me know how it goes for you.

```
-dontwarn org.xmlpull.v1.**
-keep class org.xmlpull.v1.** { *; }
-dontwarn android.content.res.XmlResourceParser
```

I ran the latest release build of my app I created with this and observed the DAV functionality working as expected.

**Comment by guillaume-tgl** [comment]
I'm very sorry for the late reply. I'm the maintainer of the library but I don't see many alternatives to SimpleXML. Any suggestion?
Would it help if I added `-dontwarn android.content.res.XmlResourceParser` to the Proguard file of the library?

**Comment by storytellerF** [comment]
> I'm very sorry for the late reply. I'm the maintainer of the library but I don't see many alternatives to SimpleXML. Any suggestion? Would it help if I added `-dontwarn android.content.res.XmlResourceParser` to the Proguard file of the library?

This is helpful.
